[package]
name = "kubie"
version = "0.6.0"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
atty = "0.2"
dirs = "2"
glob = "0.3"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
structopt = "0.3"
which = "3"
wildmatch = "1"
