[package]
name = "kubie"
version = "0.9.0"
authors = ["Simon Bernier St-Pierre <git@sbstp.ca>"]
edition = "2018"
description = "A more powerful alternative to kubectx and kubens."
keywords = ["kubernetes", "kubectx", "kubens"]
categories = ["command-line-utilities", "development-tools"]
homepage = "https://github.com/sbstp/kubie"
documentation = "https://github.com/sbstp/kubie/blob/master/README.md"
repository = "https://github.com/sbstp/kubie"
readme = "README.md"
license = "Zlib"
exclude = ["releases/**/*"]

[dependencies]
anyhow = "1"
atty = "0.2"
dirs = "2"
glob = "0.3"
lazy_static = "1"
libc = "0.2"
os_info = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
signal-hook = "0.1"
structopt = "0.3"
tempfile = "3"
which = "3"
wildmatch = "1"

[dependencies.attohttpc]
version = "0.12"
default-features = false
features = ["compress", "json", "tls-rustls"]

[profile.release]
lto = true
codegen-units = 1
